project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from project import views

urlpatterns = [
    path('i18/', include ('django.conf.urls.i18n'))
]

urlpatterns += i18n_patterns(
    path('accounts/',include("django.contrib.auth.urls")),
    path('accounts/',include("accounts.urls",namespace="accounts")),

    path('admin/', admin.site.urls ),
    path('' , views.HOME , name='home'),
    path('base/' , views.BASE , name='base'),
    
    path('products/' , views.PRODUCTS , name='products'),
    path('product_details/<str:slug>' , views.PRODUCT_DETAILS , name='product_details'),
    
    path('search/' , views.SEARCH , name='search'),
    path('contact_us/' , views.CONTACT_US , name='contact_us'),
    
    # CART------------------------------------------
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    
    # checkout------------------------------------------ 
    path('cart/checkout/',views.cart_checkout,name='cart_checkout'),
    path('placholder/',views.placholder,name='placholder'),
    
    
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_app/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _



class Categories (models.Model):
    name=models.CharField(_("name"),max_length=50)
    
    def __str__(self):
        return self.name  
    
    class Meta:
        verbose_name = (_("Categories"))
        verbose_name_plural = (_("Categories"))
        

class Brand (models.Model):
    name=models.CharField(_("name"),max_length=50)
    
    def __str__(self):
        return self.name  

class Color (models.Model):
    name=models.CharField(_("name"),max_length=50)
    code=models.CharField(_("color"),max_length=50)
    
    def __str__(self):
        return self.name  
    
class Filter_Price (models.Model):
    FILTER_PRICE= (
        ('1000 TO 2000','1000 TO 2000'),
        ('2000 TO 3000','2000 TO 3000'),
        ('3000 TO 4000','3000 TO 4000'),
        ('4000 TO 5000','4000 TO 5000'),
        ('5000 TO 6000','5000 TO 6000'),    
    )
    price=models.CharField(_("price"), choices=FILTER_PRICE ,max_length=50)
    
    def __str__(self):
        return self.price

class Products(models.Model):
    CONDITION= (('New','New'),('Old','Old'),('Header' , 'Header'))
    STOCK= (('In Stock','In Stock'),('Out Of Stock','Out Of Stock'),)
    STATUS= (('Publish','Publish'),('Draft','Draft'),)
    
    unique_id=models.CharField(unique=True ,null=True,blank=True, max_length=200 , )
    img=models.ImageField(upload_to='products/')
    name=models.CharField( max_length=50)
    price=models.IntegerField()
    price_afetr_sale=models.IntegerField(default=0)
    condition=models.CharField(choices=CONDITION , max_length=50)
    information=RichTextField( null=True )
    description=RichTextField( null=True )
    stock=models.CharField(choices=STOCK , max_length=200)
    status=models.CharField( choices=STATUS , max_length=200)
    created_date=models.DateTimeField(default=timezone.now)
    
    categories=models.ForeignKey(Categories,on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE)
    color=models.ForeignKey(Color,on_delete=models.CASCADE)
    filter_price=models.ForeignKey(Filter_Price,on_delete=models.CASCADE)
    
    slug=models.SlugField(blank=True ,null=True)

    
    
    def save (self , *args, **kwargs):
        self.slug=slugify(self.name)
        if self.unique_id is None and self.created_date and self.id:
            self.unique_id = self.created_date.strftime('75%Y%m%d23') + str(self.id)
        return super(Products,self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    
class Images(models.Model):
    img=models.ImageField(upload_to='products/')
    product=models.ForeignKey(Products,on_delete=models.CASCADE)

    def __str__(self):
        return str (self.product)

class Tags(models.Model):
    name=models.CharField(max_length=50)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    

    def __str__(self):
        return self.name



class Contact_Us (models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=200)
    subject=models.CharField(max_length=50)
    message=models.TextField(max_length=400)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email



class Order(models.Model):
    user=models.ForeignKey(User , on_delete=models.CASCADE)
    firstname=models.CharField(max_length=50)
    lastname=models.CharField(max_length=50)
    country=models.CharField(max_length=50)
    address=models.TextField(max_length=50)
    city=models.CharField(max_length=50)
    state=models.CharField(max_length=50)
    postcode=models.IntegerField(default=0)
    phone=models.CharField(max_length=50)
    email=models.EmailField(max_length=254)
    additional_info=models.TextField(max_length=1000)
    amount=models.CharField(max_length=50)
    payment_id=models.CharField(max_length=50 , blank=True ,null=True)
    baid=models.BooleanField(default=False ,null=True)
    date=models.DateField(auto_now_add=True)


    def __str__(self):
        return self.user.username
    
    
class Order_Item(models.Model):
    order=models.ForeignKey(Order , on_delete=models.CASCADE)
    product=models.CharField(max_length=50)
    img=models.ImageField(upload_to='order/')
    quantity=models.CharField(max_length=50)
    price=models.CharField(max_length=50)
    total=models.TextField(max_length=50)
    
    def __str__(self):
        return self.order.user.username

templates/main/base_generic.html
{% extends "main/base.html" %}
{% block body %}


{% block content %}
{% endblock content %}

{% endblock body %}

templates/main/contact_us.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
        <!-- Contact Area Start -->
        <div class="contact-area">
            <div class="container">
                <div class="contact-wrapper">
                    <div class="row">
                        <div class="col-12">
                            <div class="contact-form">
                                <div class="contact-title mb-30">
                                    <h2 class="title">Send A Quest</h2>
                                </div>
                                <form class="contact-form-style" action="/contact_us/" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <input name="name" placeholder="Name*" type="text" />
                                        </div>
                                        <div class="col-lg-6">
                                            <input name="email" placeholder="Email*" type="email" />
                                        </div>
                                        <div class="col-lg-12">
                                            <input name="subject" placeholder="Subject*" type="text" />
                                        </div>
                                        <div class="col-lg-12 text-center">
                                            <textarea name="message" placeholder="Your Message*"></textarea>
                                            <button class="btn btn-primary" type="submit">Send Message</button>
                                        </div>
                                    </div>
                                </form>
                                <p class="form-messege"></p>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="contact-info">
                                <div class="single-contact">
                                    <div class="icon-box">
                                        <img src="{% static 'assets/images/icons/contact-1.png' %}" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Address</h5>
                                        <p>Your address goes here. <br>
                                        123 Your Location</p>
                                    </div>
                                </div>
                                <div class="single-contact">
                                    <div class="icon-box">
                                        <img src="{% static 'assets/images/icons/contact-2.png' %}" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Phone No</h5>
                                        <p><a href="tel:0123456789">+012 345 67 89</a></p>
                                        <p><a href="tel:0123456789">+012 345 67 89</a></p>
                                    </div>
                                </div>
                                <div class="single-contact m-0">
                                    <div class="icon-box">
                                        <img src="{% static 'assets/images/icons/contact-3.png' %}" alt="">
                                    </div>
                                    <div class="info-box">
                                        <h5 class="title">Email/Web</h5>
                                        <p><a href="mailto:demo@example.com">demo@example.com</a></p>
                                        <p><a href="https://www.example.com/">www.example.com</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact Area End -->
        <!-- map Area Start -->
        <div class="contact-map my-1">
            <div id="mapid">
                <div class="mapouter">
                    <div class="gmap_canvas">
                        <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=121%20King%20St%2C%20Melbourne%20VIC%203000%2C%20Australia&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed"></iframe>
                        <a href="https://sites.google.com/view/maps-api-v2/mapv2"></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- map Area End -->
{% endblock body %}

templates/main/product_details.html
{% extends "main/base.html" %}
{% load static %}

{% block body %}
<div class="product-details-area pt-100px pb-100px">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                <!-- Swiper -->
                <div class="swiper-container zoom-top">
                    <div class="swiper-wrapper">

                        {% for i in product_details.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" src="{{i.img.url}}" style='height: 70vh;' alt="">
                            <a class="venobox full-preview" data-gall="myGallery" href="{{i.img.url}}">
                                <i class="fa fa-arrows-alt" aria-hidden="true"></i>
                            </a>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <div class="swiper-container mt-20px zoom-thumbs slider-nav-style-1 small-nav">
                    <div class="swiper-wrapper">
                        {% for i in product_details.images_set.all %}
                        <div class="swiper-slide">
                            <img class="img-responsive m-auto" style='height: 20vh;' src="{{i.img.url}}" alt="">
                        </div>
                        {% endfor %}
   
                    </div>
                    <!-- Add Arrows -->
                    <div class="swiper-buttons">
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                <div class="product-details-content quickview-content ml-25px">
                    <h2>{{product_details.name}}</h2>
                    <div class="pricing-meta">
                        <ul class="d-flex">
                            <li class="new-price"> SR {{product_details.price}}</li>
                        </ul>
                    </div>
                    <div class="pro-details-rating-wrap">
                        <div class="rating-product">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </div>
                        <span class="read-review"><a class="reviews" href="#">(5 Customer Review)</a></span>
                    </div>
                    <p class="mt-30px">{{product_details.description|truncatewords:70|safe}}</p>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>SKU:</span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">Ch-256xl</a>
                            </li>
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span> {{product_details.categories}}</span>
                        <ul class="d-flex">
                            <li>
                                <a href="#">Smart Device, </a>
                            </li>
                            <li>
                                <a href="#">ETC</a>
                            </li>
                        </ul>
                    </div>
                    <div class="pro-details-categories-info pro-details-same-style d-flex m-0">
                        <span>Tags: </span>
                        <ul class="d-flex">

                            {% for i  in product_details.tags_set.all  %}
                            <li>
                                <a href="#">{{i.name}}</a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    <div class="pro-details-quality">
                        {% comment %} <div class="cart-plus-minus">
                            <input class="cart-plus-minus-box" type="text" name="qtybutton" value="1" />
                        </div> {% endcomment %}
                        <div class="pro-details-cart">
                            <a href="{% url 'cart_add' product_details.id %}">Add To Cart</a>

                        </div>
                        <div class="pro-details-compare-wishlist pro-details-wishlist ">
                            <a href="wishlist.html"><i class="pe-7s-like"></i></a>
                        </div>
                        <div class="pro-details-compare-wishlist pro-details-wishlist ">
                            <a href="compare.html"><i class="pe-7s-refresh-2"></i></a>
                        </div>
                    </div>
                </div>
                <!-- product details description area start -->
                <div class="description-review-wrapper">
                    <div class="description-review-topbar nav">
                        <button data-bs-toggle="tab" data-bs-target="#des-details2">Information</button>
                        <button class="active" data-bs-toggle="tab" data-bs-target="#des-details1">Description</button>
                        <button data-bs-toggle="tab" data-bs-target="#des-details3">Reviews (02)</button>
                    </div>
                    <div class="tab-content description-review-bottom">
                        <div id="des-details2" class="tab-pane">
                            <div class="product-anotherinfo-wrapper text-start">
                                {{product_details.information|safe}}
                            </div>
                        </div>
                        <div id="des-details1" class="tab-pane active">
                            <div class="product-description-wrapper">
                                <p>{{product_details.description|truncatewords:50|safe}}</p>
                            </div>
                        </div>
                        <div id="des-details3" class="tab-pane">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="review-wrapper">
                                        <div class="single-review">
                                            <div class="review-img">
                                                <img src="{% static 'assets/images/review-image/1.png' %}" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>
                                                        Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula. Phasellus quam nisi, congue id nulla.
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="single-review child-review">
                                            <div class="review-img">
                                                <img src="{% static 'assets/images/review-image/2.png' %}" alt="" />
                                            </div>
                                            <div class="review-content">
                                                <div class="review-top-wrap">
                                                    <div class="review-left">
                                                        <div class="review-name">
                                                            <h4>White Lewis</h4>
                                                        </div>
                                                        <div class="rating-product">
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                            <i class="fa fa-star"></i>
                                                        </div>
                                                    </div>
                                                    <div class="review-left">
                                                        <a href="#">Reply</a>
                                                    </div>
                                                </div>
                                                <div class="review-bottom">
                                                    <p>Vestibulum ante ipsum primis aucibus orci luctustrices posuere
                                                        cubilia Curae Sus pen disse viverra ed viverra. Mauris ullarper
                                                        euismod vehicula.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="ratting-form-wrapper pl-50">
                                        <h3>Add a Review</h3>
                                        <div class="ratting-form">
                                            <form action="#">
                                                {% comment %} <div class="star-box">
                                                    <div class="rating-product">
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                        <i class="fa fa-star"></i>
                                                    </div>
                                                </div>
                                                <div class="row"> {% endcomment %}
                                            
                                                    <div class="col-md-12">
                                                        <div class="rating-form-style form-submit">
                                                            <textarea name="Your Review" placeholder="Message"></textarea>
                                                            <button class="btn btn-primary btn-hover-color-primary " type="submit" value="Submit">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- product details description area end -->
            </div>

        </div>
    </div>
</div>
{% endblock body %}